from app.db.database import get_connection
from app.services.embeddings import get_query_embedding


def get_listing_stats() -> dict:
    """Fetch aggregate stats so the LLM knows the full picture."""
    try:
        conn = get_connection()
        cur = conn.cursor()
        cur.execute("""
            SELECT COUNT(*) as total,
                   COUNT(DISTINCT location) as areas,
                   ROUND(AVG(rent)) as avg_rent
            FROM listings;
        """)
        row = dict(cur.fetchone())

        cur.execute("""
            SELECT location, COUNT(*) as count
            FROM listings
            WHERE location IS NOT NULL
            GROUP BY location
            ORDER BY count DESC;
        """)
        by_area = ", ".join(f"{r['location']} ({r['count']})" for r in cur.fetchall())

        cur.close()
        conn.close()
        return {
            "total": row["total"],
            "areas": row["areas"],
            "avg_rent": row["avg_rent"] or 0,
            "by_area": by_area or "N/A"
        }
    except Exception as e:
        print(f"Stats query failed: {e}")
        return {"total": "unknown", "areas": "unknown", "avg_rent": "unknown", "by_area": "N/A"}


def search_listings(
    query: str,
    limit: int = 6,
    max_rent: int = None,
    bhk: str = None,
    location: str = None,
    brokerage: bool = None,
    amenities: list[str] = None
) -> list[dict]:

    try:
        query_embedding = get_query_embedding(query)
        print(f"Embedding generated, length: {len(query_embedding)}")
    except Exception as e:
        print(f"Embedding failed: {e}")
        return []

    # Serialize as postgres vector literal — most reliable approach
    vec_str = "[" + ",".join(map(str, query_embedding)) + "]"
    print(f"DEBUG vec_str length: {len(vec_str)}, starts: {vec_str[:30]}, ends: {vec_str[-30:]}")

    filters = []
    filter_params = []

    if max_rent:
        filters.append("l.rent <= %s")
        filter_params.append(max_rent)
    if bhk:
        filters.append("l.bhk ILIKE %s")
        filter_params.append(bhk)
    if location:
        filters.append("l.location ILIKE %s")
        filter_params.append(f"%{location}%")
    if brokerage is not None:
        filters.append("l.brokerage = %s")
        filter_params.append(brokerage)
    if amenities:
        filters.append("l.amenities && %s")
        filter_params.append(amenities)

    where = ("WHERE " + " AND ".join(filters)) if filters else ""

    try:
        conn = get_connection()
        cur = conn.cursor()

        # Increase probes to search more IVFFlat clusters (default 1 is too low for small datasets)
        cur.execute("SET LOCAL ivfflat.probes = 10;")

        # Embed vec_str directly into SQL string — not as a param
        # This is safe here because vec_str is generated by us, not user input
        query_sql = f"""
            SELECT
                l.id, l.source, l.location, l.rent, l.bhk,
                l.amenities, l.contact, l.posted_at, l.brokerage,
                1 - (l.embedding <=> '{vec_str}'::vector) AS similarity
            FROM listings l
            {where}
            ORDER BY l.embedding <=> '{vec_str}'::vector
            LIMIT %s;
        """

        print(f"DEBUG sql preview: {query_sql[:200]}")

        cur.execute(query_sql, filter_params + [limit])

        results = [dict(r) for r in cur.fetchall()]
        print(f"Search returned {len(results)} listings")
        cur.close()
        conn.close()
        return results

    except Exception as e:
        print(f"Search failed: {e}")
        import traceback
        traceback.print_exc()
        return []
    